/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/W3WnYzWtGfb
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import SideBar from "./sidebar";

export default function NewWord() {
  return (
    <div className="grid gap-4 md:grid-cols-[250px_1fr] lg:grid-cols-[300px_1fr]">
      <div className="hidden flex-col gap-2 md:flex">
        <SideBar />
      </div>
      <div className="flex flex-col gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Add a New Word</CardTitle>
            <CardDescription>
              Contribute to the 3erben Dictionary by adding a new word.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="word">Word</Label>
                <Input id="word" placeholder="Enter the word" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="definition">Definition</Label>
                <Textarea id="definition" placeholder="Enter the definition" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="example">Example Sentence</Label>
                <Textarea
                  id="example"
                  placeholder="Provide an example sentence"
                />
              </div>
              <Button className="w-full" type="submit">
                Submit Word
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
